### ISSUE TITLE
No connection to private tracker

### ISSUE THREAD

**Issue by Sylphe** [hadouken/hadouken#102]
It might seem the custom user agent does not pass certain private trackers:
On some of them it connects , but in the peerlist the user agent is blank, and on some others, hadouken says it connected, but the client doesnt show up in the peerlist and there is no up and down.

Since for now there is no way to get a  error message from the tracker, maybe changing it to a libtorrent 1.X.X would be better

**Comment by vktr** [comment]
I'm aware of problems since I added our own peer ID in #87. The question is, do we change back or do we try to get the peer ID accepted?

**Comment by Sylphe** [comment]
90% of the private trackers are absolutely not interested in new clients or even betas of client,and will recommend old and proven stable versions, their approved lists are usually very small. I think getting the peerid accepted will be a long effort for not much reward due to the popularity of this client which will remain a niche one, at least for the time being.

I would actively recommend changing to a generic lib torrent user agent. 

I also saw that the user agent is the only option you didn't include in the lib torrent advanced settings, I believe it's a good point to prevent people messing around with it, and to gain confidence from private trackers ( this was why tixati was banned everywhere at first, and as you can see it does not remain unbanned in most places )

maybe an option to switch between the current libtorrent version number and the hadouken user agent if people want to could added

**Comment by vktr** [comment]
One solution is to keep the libtorrent user agent, and have `HA` as the peer ID. However this is not totally honest if ever a tracker tries to connect to the announcing client.

If there's not much reward in trying to get the peer ID and user agent accepted, then perhaps it's better to keep it on libtorrent defaults.

**Comment by Sylphe** [comment]
Sorry I actually meant hadouken user agent and version , and lib torrent user agent and version, a mix of both as you stated above will no be honest.
But I will still recommend lib torrent default only

**Comment by Sylphe** [comment]
If you want to push this , ill download the appveyor build and test some more, right now without private tracker support its very restricted.
Id like to test how HDK behaves as intial seeder on some trackers.

**Comment by vktr** [comment]
I'll push a new build today.

**Comment by vktr** [comment]
The v5 code will use the default libtorrent peer ID and user agent.

**Comment by charsi** [comment]
Facing same issue with some private trackers. No peers being connected. What peer ID, user agent does hadouken use now?

**Comment by vktr** [comment]
It uses the default libtorrent peer ID and user agent.

**Comment by charsi** [comment]
Is it possible to change this without having to build it myself? I think the tracker I am using only allows rtorrent, utorrent and deluge.

**Comment by vktr** [comment]
No
