### ISSUE TITLE
feature Request : rss refresh rate

### ISSUE THREAD

**Issue by Sylphe** [hadouken/hadouken#103]
The RSS refresh rate of hadouken is minimum 5 minutes.

However on fast private trackers , most races happen during that time span since racers use clients that have faster rss refresh rate (in the case the website ttl allows it ofc) . By the time clients like utorrent or deluge join the race with their 5 min refresh rate , it is already over.

An example would be the refresh rate of QBitorrent which can go to 1 minute, or BYteflood which is in seconds.

Although this feature will only target a small amount of people using the client ,I'd be glad to have a refresh rate of 1 minute , or even less

**Comment by vktr** [comment]
In the upcoming v5 release, the minimum TTL (refresh rate) is one minute - see [the docs](http://docs.hdkn.net/en/latest/configuration/rss.html).
