### ISSUE TITLE
Finished to seeding bug

### ISSUE THREAD

**Issue by Sylphe** [hadouken/hadouken#104]
I imported some torrents from Qbt.

One of them had excluded one file, downloaded the rest, so was considered 100% and seeding by Qbt
Hadouken detected that, but it seems the file that was specified as do not download prevents hadouken from entering seed mode. It just lists as finished, and never enters seeding.

I tested this on one of the few trackers that allow HDK and it seems the client just doesnt connect, although it lists some peers in the peerlist tab ( ould it be scrape data ?)

**Comment by Sylphe** [comment]
when deleting and re adding the torrent manually, i encounter the same bug as #80 since the torrent contains accents, it detects existing file names, starts hash for half a second, but proceeds to download the files with the messed up encoding next to the existing ones.

**Comment by vktr** [comment]
Thanks, I'll look into it.

**Comment by vktr** [comment]
File encoding issue should be resolved with the v5 merge. The finished will be fixed in the client.
