### ISSUE TITLE
v5 discussion

### ISSUE THREAD

**Issue by vktr** [hadouken/hadouken#108]
Some background - I'm currently working on the next major version (v5) of Hadouken. It will be rewritten in C++11 and available for Windows, Linux and OSX. Other than the language switch, it will work much like the current version with a HTTP/JSONRPC API and plugin support.

I currently have it running on Windows and Ubuntu. Next in line is to run it on the new Raspberry Pi 2. The OSX build is also a high priority.

 * Based on [Poco](http://pocoproject.org/) for the application framework.
 * [Rasterbar-libtorrent](http://libtorrent.org/) is still the BitTorrent library.
 * It will have a plugin support built on top of the plugin framework in Poco.

I'm opening this issue to get input. If there is anything you miss in the current version that you want in v5, bring it up for discussion!

**Comment by Sylphe** [comment]
I think the GUI needs a general redesign with better sorting options and actions that can span multiple torrents at once. Right now its very impractical if you have more than a dozen torrents to manage
Notification of tracker error messages or others
A torrent creating option would be nice.
I have not managed to make the RSS feed and auto download work properly,

**Comment by vktr** [comment]
@Sylphe I'm currently rethinking the GUI part and I'm not sure Hadouken should have a GUI built in. I believe a native desktop application is better and easier to use. It would of course just be a thin client connecting to Hadouken, but still behave like a desktop application.

This way, Hadouken can focus on doing one thing well (ie. being awesome at managing and downloading torrents), and the client can feel native to each desktop.

We could still have a tiny embedded GUI in Hadouken which lists torrents - but the real client would be the desktop client.

Opinions?

**Comment by Sylphe** [comment]
My choice of wording was bad I think. what i meant was the web interface : the current way you access Hadouken on localhost ,something similar to the Deluge web interface  that you access as well on localhost. .

Although the Deluge web Interface is clearly ugly, it is more practical at managing stuff. 
![capture](https://cloud.githubusercontent.com/assets/9304246/6349840/53d738d0-bbe3-11e4-8074-e78be6a14ce0.PNG)

I personally have been using just the web client for over a month due to the main deluge client having multiple ram leaks and cpu hogging bugs and i feel that it has managed to replace the desktop client  completely.  

The thin client could also be a good idea, but if the current web interface is well done i think it becomes less necesaary, but more of a nice addition

What do you think ?

**Comment by vktr** [comment]
I understand - and I also think the embedded web interface in Hadouken is missing a lot of nice things. Most of those things would be very easy to implement in a thin client.

For example,

 * Notifications/balloon popups
 * Handle .torrent files
 * Desktop integration (Send torrent to Hadouken, etc)
 * etc

What I mean is that it may be easier to write a thin desktop client than to make a web page emulate it. Particularly when it comes to handling files and integrating with the desktop.

**Comment by Sylphe** [comment]
I get it, I think its better the way you mentioned it then.

**Comment by jkaberg** [comment]
With a proper API an WebUI wouldn't be far off for a thirdparty developer ;)

**Comment by vktr** [comment]
@jkaberg Yeah, something like that :) I know there is at least one third-party web UI in the works, along with the desktop client at https://github.com/hadouken/krang.

**Comment by jkaberg** [comment]
Any eta on an offical release of v5? :-)

(mellan tummen å pekfringret som vi säger ;-)

**Comment by vktr** [comment]
@jkaberg first half of April is an educated guesstimate. There's not much missing from Hadouken itself, I've even [documented most if it](http://docs.hdkn.net). Here what's missing,

 * Build instructions for Linux (Debian/Ubuntu).
 * Some small things at remote.hdkn.net.
 * A first-time user guide of some sort.

Not much in the coding department, which is good :)

**Comment by Sylphe** [comment]
I'm impatient to try v5 as well.

**Comment by vktr** [comment]
- [x] [Build instructions for Linux (Ubuntu)](http://docs.hdkn.net/en/latest/installing/ubuntu.html)
- [x] [Getting started guide](http://docs.hdkn.net/en/latest/getting-started.html)

I'll do some final touches on [remote.hdkn.net](http://remote.hdkn.net) this week and we'll make sure Hadouken is released by Monday at the latest.

**Comment by vktr** [comment]
Sorry, this is taking some time... I'm stacked with real life and in the middle of a big refactoring of Hadouken. It now has a JS API which should be quite sweet once it's done, and as soon as I finish it I'll release something!

**Comment by Sylphe** [comment]
No Stress

**Comment by SirTerrific** [comment]
Hi,

How can we install Krang please ? :).

Thx for your work

**Comment by vktr** [comment]
@SirTerrific Hi, sorry for the late answer.

Krang is not finished yet. The "official" v5 client is located at http://remote.hdkn.net, and the source is at https://github.com/hadouken/remote.

**Comment by vktr** [comment]
Hi all, sorry for the super-delayed release.

I'm currently fixing the last issues and features for v5 and it should be ready and released quite soon. If you haven't already, I'd recommend at least reading through [the docs](http://docs.hdkn.net) to get acquainted with v5.

**Comment by jkaberg** [comment]
Does it support https? I recon ppl (seeing as its torrents and all that) want security/privacy :smile:

**Comment by vktr** [comment]
@jkaberg HTTPS for what? The built-in HTTP API? If so, then yes :smile:

**Comment by jkaberg** [comment]
Goodie! Awesome work @vktr

**Comment by vktr** [comment]
Hi all, some updates.

As soon as #142 is merged and done I will begin to prepare the release of 5.0.

**Comment by jwillmer** [comment]
percect, happ to hear! :+1:

**Comment by vktr** [comment]
Done, and done! Just published [v5](https://github.com/hadouken/hadouken/releases/tag/v5.0.0).

:shipit:
