### ISSUE TITLE
Contribution/Development README

### ISSUE THREAD

**Issue by senbrow** [hadouken/hadouken#109]
It would be great to have a document that provides a explicit list of which tools and libraries and you need to build and run Hadouken from source, as well as a set of do's and don'ts for contributing to the project.

Something like:

# Building Hadouken
### Things you'll need
* libpackage
* Visual Hadouken 2015
* ...

### Running the code
1. Invoke `buildHadouken.bat` from a command prompt.
2. Sacrifice a goat
3. Run `hadouken.exe`

#### Do
* Work outside of master
* Submit detailed pull requests

#### Don't
* Commit your private RSA key

**Comment by vktr** [comment]
Added better build instructions and contributor guidelines in 216718592b671ceb59b5a3966e8fcabd02a444d1.
