### ISSUE TITLE
Documentation for RSS

### ISSUE THREAD

**Issue by phrusher** [hadouken/hadouken#111]
Been trying to add a few sources without success. At least that is what I thought but this morning I noticed a new torrent downloading so perhaps I got it kind of right? Although I don't have AutoStart in my filter but still it started to download automatically. So if there could be some kind of documentation, that would be great.

**Comment by vktr** [comment]
Fixed for the upcoming v5 release, http://docs.hdkn.net/en/latest/configuration/rss.html.
