### ISSUE TITLE
Unable to choose username / password during install

### ISSUE THREAD

**Issue by sammie11** [hadouken/hadouken#115]
Hi

According to the guide there you should get to choose settings like username, password and port. This does not happen when I install hdkn. I've tried to login to the webui with hdkn/hdkn as user/pw but without success. I'm running Windows 7 Pro N and been using the install file named "hadouken-4.7.0.msi". What to do?

Thank you in advance!

**Comment by vktr** [comment]
The guide is for the (unreleased) v5 of Hadouken. If you're running v4.x you will be prompted to create an account when you access the web UI for the first time.

**Comment by sammie11** [comment]
I see. I didn't get the opportunity to create an account on the first try but now it worked so thanks a lot!
