### ISSUE TITLE
(Very minor) Build on RPi B+ notifies of deprecated calls

### ISSUE THREAD

**Issue by OscarAlmgren** [hadouken/hadouken#118]
Using the installation guide for Ubuntu and installing on my RPi B+ I get a lot of warnings when building during rastbar installation. 
$ ./configure --disable-deprecated-functions
Ok etc.
$ make && sudo make install 
...
/tmp/ccMTBsEm.s: Assembler messages:
/tmp/ccMTBsEm.s:644: Warning: swp{b} use is deprecated for ARMv6 and ARMv7

And a lot of these lines. No warnings or errors break the build. Just a reflection to maybe update the swp call to something for the mentioned ARMv6 and v7?

**Comment by vktr** [comment]
I don't really have control of the libtorrent code base, but I can't remember getting any warnings when building with GCC 4.8. Which version are you using?

**Comment by OscarAlmgren** [comment]
Seems to be 4.6.3 rpi edition.

oscar@raspberrypi ~ $ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.6/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Debian 4.6.3-14+rpi1' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.6.3 (Debian 4.6.3-14+rpi1)

**Comment by vktr** [comment]
There are 4.8 packages available, `gcc-4.8` and `g++-4.8` which didn't produce warnings for me. Perhaps you can try these, or seeing as this is a minor issue in libtorrent, we'll close this :)

**Comment by OscarAlmgren** [comment]
Yes, I'll try and see if that works instead.
