### ISSUE TITLE
Please update the docu

### ISSUE THREAD

**Issue by jwillmer** [hadouken/hadouken#128]
The current version has nothing to do with the docu and I am not able to connect to the gui from a remote pc.

Edit: I now managed to get all working but the docu is confusing because it is to old. Without the docu I would have been faster ;-)

**Comment by vktr** [comment]
Hi, sorry for the confusion. The documentation at docs.hdkn.net is for the upcoming v5 release which is  currently in beta.

**Comment by vktr** [comment]
Closing this as [v5](https://github.com/hadouken/hadouken/releases/tag/v5.0.0) was just released, which means [the documentation](http://docs.hdkn.net) is current.
