### ISSUE TITLE
Downloads stuck in DownloadingMetadata if recieved via CouchPatato

### ISSUE THREAD

**Issue by jwillmer** [hadouken/hadouken#129]
If added manually it starts to download. Logfile looks similar for both actions.

**Comment by vktr** [comment]
I can reproduce this.

The cause is missing trackers. The CouchPotato integration I wrote sends a list of trackers but Hadouken does not add them to the torrent.

This will be fixed in v5.

**Comment by vktr** [comment]
Fixed in 4113ace29f98770f3c432b33c4f19341ad4f52ba.
