### ISSUE TITLE
Support for Labels

### ISSUE THREAD

**Issue by Sinvex** [hadouken/hadouken#148]
Love Hadouken, would love to see support for labels added back in, they were stripped out with the v5 rewrite.

**Comment by vktr** [comment]
Hadouken has support for tags, which I guess is what you're looking for :smile: 

What with labels/tags would you like to see?

**Comment by Sinvex** [comment]
Sorry, I didn't see any mention of them in the documentation for the "session.addTorrentFile" I do however see the option in the jsonrpc source. Can you update your sonarr pull request to support them like other clients do? With a 'category' field, and an option to remote, so that it's possible to quickly filter which torrents are shown by tag/label. 

I manage hundreds and sometimes thousands of torrents at a time. I need a clicky list that shows how many torrents there are in which category, that I can click to show me just the torrents in the category (for example a list of tags on the left such as "All", "TV", "Movies", "Comics" etc and when you click on a category it will display just the torrents marked with that tag. Deluge label system is a good example if you're familiar with it at all.

**Comment by vktr** [comment]
Yeah, they're kinda undocumented at the moment. They are a part of the new metadata API surrounding torrents which came in v5.

I'll make sure to update the Sonarr PR in the coming days, as well as updating the remote to filter on tags.

**Comment by Sinvex** [comment]
Good deal, and thanks for the quick responses. You're great!

**Comment by vktr** [comment]
Label support was added in aee8f1c600245f2be0fb4f2a2a35a67a5b0642b3.
