### ISSUE TITLE
Create torrent plugin

### ISSUE THREAD

**Issue by vktr** [hadouken/hadouken#15]
A simple plugin for creating torrents from files/folders running Hadouken. This should be released as a plugin.

Basic workflow:
- Click "Create torrent" in toolbar
- Select file/folder
- Set some options (such as "Add to download queue")
- Click "Create" to have Hadouken create the torrent and either stream it to the browser or save it on the computer running Hadouken (or both).

**Comment by maxpil** [comment]
where can I find this plugin?

**Comment by vktr** [comment]
I never got around doing this.
