### ISSUE TITLE
Details in MSI package

### ISSUE THREAD

**Issue by yoGhurrt1** [hadouken/hadouken#152]
There is some missed text in two places in Installer. First - it's on the ending screen, when you'll cancel your instalation, window looks like this
![hadouken1](https://cloud.githubusercontent.com/assets/13383620/8751940/d945de34-2cb0-11e5-9458-56d2c3c29ac6.jpg)
Second one is on customization features screen. 
![hadouken2](https://cloud.githubusercontent.com/assets/13383620/8751987/55444fb6-2cb1-11e5-948c-598aa592e802.jpg)

**Comment by vktr** [comment]
Thanks, I'll make sure this is fixed in v5.1.
