### ISSUE TITLE
Still making uTP connections when disabled.

### ISSUE THREAD

**Issue by zp** [hadouken/hadouken#164]
It appears that hadouken is still making uTP connections when it's set to disabled in the hadouken.json config and when applying it in the web ui. (or at least the peers tab is saying that it's making utp connections)

````
"utp": {
  "enabled": false
},
````

![](http://i.imgur.com/yQbOjum.png)

This is running on Arch Linux, built from 5.1 develop branch 8ff78bd

**Comment by vktr** [comment]
I'll have a look! Thanks!

**Comment by vktr** [comment]
So, the option you showed in the screenshot, `Enable bandwidth management [uTP]` isn't actually enabling/disabling uTP but enables/disables bandwidth throttling (gives uTP the same prio as TCP).

I've added the option to enable/disable uTP in PR #169. It uses the same configuration key that you tried with, which doesn't exist right now, but should.
