### ISSUE TITLE
WebUI becomes increasingly unreponsive during high download speeds.

### ISSUE THREAD

**Issue by zp** [hadouken/hadouken#165]
After setting up hadouken on my linux seedbox for testing, I've found that the webui becomes unresponsive depending on how fast you're downloading at.

In my case, once you hit around 8-9 MB/s or higher download speeds, the webui basically freezes and stops updating until the torrent completes or the download speeds go lower than 8-9 MB/s

This basically renders hadouken unsuitable for high bandwidth / seedbox purposes at the moment. (at least on a remote server, might be fine on a local machine/network)

The web ui's for Deluge, Transmission, and rTorrent (ruTorrent) have no problems updating/refreshing when downloading/uploading at 10-12+ MB/s on the same server that hadouken is running on.

Not sure if there's anybody else running hadouken on a linux machine with a 100 megabit or higher connection that can chime in with their experiences.

**Comment by vktr** [comment]
I'll see if I can reproduce this in a virtual machine. How many concurrent downloads?

**Comment by zp** [comment]
I tested it on a single torrent that was just under 900 megabytes, it would increasingly take longer for the webui to refresh (I had it set to 1000ms refresh rate) and then eventually seemed like it would freeze completely until the torrent finished.

Even attempting to ctrl-f5 refresh the webui page didn't work.

**Comment by vktr** [comment]
Hmm... I've been hitting something similar when `libtorrent` is built with all the debug asserts. Can you make sure you don't build with `TORRENT_DEBUG`?

**Comment by zp** [comment]
It appears that the ./linux/build.sh file defaulted to compile in debug mode on my machine, after setting it to compile in release mode the webui appears to work fine when downloading at high speeds.

Guess I'll close this for now.
