### ISSUE TITLE
Documentation for RSS feeds uses invalid JSON

### ISSUE THREAD

**Issue by QWp6t** [hadouken/hadouken#175]
https://github.com/hadouken/hadouken/blob/develop/docs/src/configuration/rss.rst

All entries use `[ .. ]` to indicate an array, but then they have `"key": "value"` pairs to indicate an object.

I believe you want an array of objects here.

```
{
  "feeds": [{
    "url": "http://example.com/feed",
    "filter": "*"
  },
  {
    "url": "http://example2.com/feed2"
    "filter": "*"
  }]
}
```

Something along those lines.

**Comment by vktr** [comment]
Good catch! :+1:
