### ISSUE TITLE
Hadouken remote not longer working since version 5.1

### ISSUE THREAD

**Issue by h3llrais3r** [hadouken/hadouken#176]
Hadouken remote cannot longer connect to local hadouken server since version 5.1.
I've just rolled back to version 5.0 and I can connect again.

**Comment by vktr** [comment]
Starting in v5.1, Hadouken embeds a local webui which you can access at `http://localhost:7070/gui/index.html` after installation (if you haven't changed the port).

I'm always hestitant to break backwards compatibility - even more so when I don't want to bump the major version. However, this time around, I think it it was worth it. The remote will close down in the coming weeks/months.

**Comment by h3llrais3r** [comment]
Thanks for the feedback. I'll be checking the embedded gui then ;)
