### ISSUE TITLE
Daemon crashes when add .torrent-file with not latin name

### ISSUE THREAD

**Issue by saburovga** [hadouken/hadouken#183]
Hi Viktor.

Daemon crashes when I add .torrent-file with not latin (cyrrillic in my case)  name. I add .torrent in folder which defined in "autoadd" plugin settings. When I add this file via web-interface all works fine.

**Comment by vktr** [comment]
Hi, do you have a torrent file I can test with?

**Comment by saburovga** [comment]
Link for test file: https://drive.google.com/file/d/0B23ywalDCskTNUhzR240U0t5TTg/view?usp=sharing

**Comment by vktr** [comment]
I've located the problem, but the fix is a bit tricky (AFAIK). I'll try to make the fix for v5.3.

**Comment by Robo210** [comment]
I've got a partial fix that stops the crash and gets the torrent data into libtorrent, however, the torrent still isn't getting added for some reason.

**Comment by Robo210** [comment]
Issue should be fixed now in the develop branch.
