### ISSUE TITLE
msi package improvements and eof for json config file

### ISSUE THREAD

**Issue by rabbitsmith** [hadouken/hadouken#192]
I think the msi package can be improved to help configure some settings at install time like pushbullet configuration, automove(to specify folder using a dialog box instead of typing the location manually). Also the json config file saved after hadouken stops is not eof normalized in windows. Hadouken can be modified to write the json config file with cr and lf so that it will be easy to edit the file with notepad

**Comment by vktr** [comment]
I'm trying to keep the installer as simple as possible. Instead of putting configuration in the installer, I'm working on bringing GUI configuration to all available settings instead.

**Comment by rabbitsmith** [comment]
Ok thank you.
