### ISSUE TITLE
webui design change

### ISSUE THREAD

**Issue by rabbitsmith** [hadouken/hadouken#193]
I had been a great fan of the webui which was in hadouken 4.7.  Will the desgin principles of hadouken 5.2 webui be changed anytime soon. I am eagerly waiting to experience the webui which was in 4.7. I think the utorrent styled webui is a little old-fashioned

**Comment by vktr** [comment]
Even though the utorrent-styled webui is old-fashioned, I think it's better suited for this kind of application. I _might_ release a mobile version of the 4.7-webui but I don't think I will change the current webui anytime soon.
