### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by luxus** [hadouken/hadouken#207]
i through OS X support was planed for 5.0 ?
it is still on the roadmap?

**Comment by vktr** [comment]
Hadouken should run on OSX, however at the moment you're required to build from source. There aren't any instructions on this, but the [build instructions for Ubuntu](http://docs.hdkn.net/en/latest/building/ubuntu.html) should give a general idea of what is required.

I'll make sure to put build instructions in the documentation, and in the future also provide OSX application packages.

**Comment by luxus** [comment]
okay i will try that

**Comment by pavildon** [comment]
Im trying to hadouken to work in OSX, so far it got compiled , but when executing the binary a nasty sigfault appears and sometimes (with other compilation configuration) a bad file descriptor error displays. I think is related to some compilation warnings 

[compilation log](https://gist.github.com/5e3320ab7e568f95dfed)

**Comment by pavildon** [comment]
this is my fork https://github.com/aindigo/hadouken 
i compiled and ran hadouken without much problem

```
mkdir build
cd build
cmake .. -DBOOST_ROOT=<your boost path>
make -j 8
```

and copy webui.zip and the js folder to the resulting bin folder
ill do a pull request when i check there's no mayor problems

**Comment by vktr** [comment]
OSX support was added in #223.
