### ISSUE TITLE
--daemon option not recognized

### ISSUE THREAD

**Issue by imiric** [hadouken/hadouken#248]
Hi,

first of all, thanks for this awesome project.

I compiled Hadouken on Ubuntu 14.04 from the latest commit on `develop` (a8cff736) (because contrary to what the [installation instructions](http://hadouken.readthedocs.org/en/latest/installing/ubuntu.html) say, the .deb package is _not_ available on the [releases page](https://github.com/hadouken/hadouken/releases) (should this be another GitHub issue?)), but can't seem to get the `--daemon` option to work at all:

``` bash
hadouken@nas:~$ hadouken --daemon
[2016-04-14 20:11:37.331894] [0x00007f84184bf780] [error]   unrecognised option '--daemon'

Allowed options:
  --config arg          Set path to a JSON configuration file. The default is
                        %appdir%/hadouken.json
  --daemon              Start Hadouken in daemon/service mode.

hadouken@nas:~$ 
```

Another strange thing is that `--daemon` (and presumably other options) are missing from the `--help` output:

``` bash
hadouken@nas:~$ hadouken --help
Allowed options:
  -h [ --help ]         Display available commandline options
  --config arg          Set path to a JSON configuration file. The default is
                        %appdir%/hadouken.json

hadouken@nas:~$ 
```

... yet when passing unrecognized options, `--daemon` is shown:

``` bash
hadouken@nas:~$ hadouken --asdasd
[2016-04-14 20:11:43.056693] [0x00007fa04959e780] [error]   unrecognised option '--asdasd'

Allowed options:
  --config arg          Set path to a JSON configuration file. The default is
                        %appdir%/hadouken.json
  --daemon              Start Hadouken in daemon/service mode.

hadouken@nas:~$ 
```

(Also, small sidenote, but "%appdir%" is only relevant on Windows, so it shouldn't be shown on other platforms.)

Thanks for your work!

Ivan

**Comment by vktr** [comment]
Hi! Thanks for the feedback, always welcome 😄 The `--daemon` flag has been brought up before, in #232 and #240, and we have no solution yet.

The `.deb` file was removed from the releases page since it didn't work 100%, so the better solution is to let users on Linux compile Hadouken themselves.

**Comment by imiric** [comment]
Thanks for the quick response.

It's not a problem if it doesn't work, as it's trivial to create an Upstart/systemd service for it (or just use [daemonize](http://software.clapper.org/daemonize/)). It's just a bit surprising to see it advertised as a headless BT client and Linux daemon if it doesn't support this natively.

Anyway, feel free to close this issue, and sorry for the duplicate report.

**Comment by vktr** [comment]
Yeah, the idea has always been to run as a regular daemon on Linux and we should definitely fix it :smile:
