### ISSUE TITLE
Where is the .deb?

### ISSUE THREAD

**Issue by wsw70** [hadouken/hadouken#266]
Hello

Sorry if I missed an obvious download link but where is the .deb package for Debian? The documentation points to the [Ubuntu installation page](http://docs.hdkn.net/en/latest/installing/ubuntu.html) which in turn points to the releases on Github which hold only the Windows version and the source code.

Thank you for any pointer

**Comment by vktr** [comment]
Hi! The .deb package was removed since it didn't work as expected. You can try to build the latest version from source instead.
