### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by jkaberg** [hadouken/hadouken#46]
Let me be the first one (and most certainly not the last!) to request support for linux (debian/ubuntu ++), while Windows is great and all, most people run thire media servers (and many media players aswell, hint hint openelec.tv) on linux platforms  

If you dont have any plans on a linux port I would suggest you make this clear in the README as I'm quite sure this will be a very requested feature to come

PS: I love the idea of this project, well done!

**Comment by vktr** [comment]
Just merged in the v5 code, which builds on Linux. Closing this.
