### ISSUE TITLE
Add seeding goals [Feature]

### ISSUE THREAD

**Issue by sammy2142** [hadouken/hadouken#82]
Some user adjustable seeding goals would be awesome :)
If specified seed ratio is met stop the torrent
If specified seed duration is reached stop the torrent etc

Seeding Goals are extremely useful for automated/unattended setups (i.e. using hadouken with couchpotato, sonarr/nzbdrone, sickrage/sickbeard) as these programs usually have methods built into them to remove/cleanup torrents once it has met seeding goals (and of course imported properly).

Edit: Looking through the advanced options there appears to be these options built in:
bt.net.seed_time_limit    86400 (24 hours?)
bt.net.seed_time_ratio_limit    7

But I cant seem to find any option to tell it what to do when it reaches these goals (stop_seed_at_ratio: True etc)

**Comment by jwillmer** [comment]
yes, that would be nice @swangy . After seeding goal reached it should be moved into folder "complete".

**Comment by vktr** [comment]
Fixed in #141.

**Comment by sammy2142** [comment]
Awesome - thank you :)
