### ISSUE TITLE
IP Filter Plugin

### ISSUE THREAD

**Issue by mercyking1** [hadouken/hadouken#95]
Would like to see an IP Filter plugin - to subscribe to a feed of blocked IP addresses and block connections to those IPs within Hadouken.  This is a common functionality in popular torrent clients.

**Comment by Sylphe** [comment]
Blocklists for torrents are useless by giving users a false sense of security, and also preventing  from connecting to good ip adresses by banning good ip ranges.

Organisations that monitor certain torrent don't need to connect to you for them to send you a notice, they see you in the swarm, this is called the indirect method, the direct method 5 (connecting and seeing if you send to them/send to you) is older and not as commonly in use now as it used to be before..

I don't think this feature should be added.
